apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: sim
  name: simulator
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sim
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sim
    spec:
      containers:
      - image: kodekloud/event-simulator
        imagePullPolicy: Always
        name: sim-app
    