apiVersion: v1
kind: Service
metadata:

  labels:
    app: sim
  name: sim-svc
  
  
spec:
  ports:
  - port: 82
    protocol: TCP
    targetPort: 82
  selector:
    app: sim

  type: NodePort
status:
  loadBalancer: {}