apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-27T22:49:51Z"
  labels:
    app: nginx
  name: test-svc
  
  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}