apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-11-27T22:49:51Z"
  labels:
    app: nginx
  name: test-svc
  namespace: default
  resourceVersion: "2149497"
  uid: bebce582-08e4-4c0d-ab82-68d680b6acb1
spec:
  clusterIP: 10.100.161.113
  clusterIPs:
  - 10.100.161.113
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}