apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: ecommerce
  name: ecommerce
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      containers:
      - image: kodekloud/ecommerce
        imagePullPolicy: Always
        name: e-com
    