apiVersion: v1
kind: Service
metadata:

  labels:
    app: ecommerce
  name: ecom-svc
  
  
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: ecommerce

  type: NodePort
status:
  loadBalancer: {}